[project]
name = "smart-mcp-proxy"
version = "0.1.0"
description = "Smart MCP Proxy - A federating gateway for MCP servers with intelligent tool discovery"
readme = "README.md"
requires-python = ">=3.11.1"
dependencies = [
    "fastmcp>=2.7.1",
    "faiss-cpu>=1.7.4",
    "sentence-transformers>=2.2.2",
    "openai>=1.0.0",
    "scikit-learn>=1.3.0",
    "httpx>=0.25.0",
    "pydantic>=2.0.0",
    "numpy>=1.24.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
